# Generated by Django 4.0.4 on 2022-05-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='logo_post',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
