# Generated by Django 4.0.4 on 2022-05-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fixing_status',
            field=models.IntegerField(choices=[(0, 'Not fixed'), (1, 'Fixed Left'), (2, 'Fixed Right')], default=0),
        ),
    ]
