# Generated by Django 4.0.4 on 2022-05-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postcategory_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='category_color',
            field=models.CharField(default='#0074D9', max_length=7),
        ),
    ]
